name: common
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: teja <email@example.com>

environment:
  sdk: '>=2.1.1 <3.0.0'

dependencies:
  jaguar_serializer: ^2.2.10
  crossplat_objectid:
  jaguar_retrofit:
  date_format: ^1.0.6
  open_weather_api: ^1.5.5

dev_dependencies:
  test: ^1.0.0
  build_runner:
  jaguar_serializer_cli:
  jaguar_retrofit_gen: